#include "SDL.hpp"

extern "C" int luaopen_SDL_events(lua_State *state)
{
	luaL_newmetatable(state, SDL_METATABLE);
	struct {
	 const char *name;
	 lua_Integer value;
	}
	args [] =
	{
	// SDL_EventType
	ARG(QUIT)
	ARG(APP_TERMINATING)
	ARG(APP_LOWMEMORY)
	ARG(APP_WILLENTERBACKGROUND)
	ARG(APP_DIDENTERBACKGROUND)
	ARG(APP_WILLENTERFOREGROUND)
	ARG(APP_DIDENTERFOREGROUND)
	ARG(WINDOWEVENT)
	ARG(SYSWMEVENT)
	ARG(KEYDOWN)
	ARG(KEYUP)
	ARG(TEXTEDITING)
	ARG(TEXTINPUT)
	ARG(MOUSEMOTION)
	ARG(MOUSEBUTTONDOWN)
	ARG(MOUSEBUTTONUP)
	ARG(MOUSEWHEEL)
	ARG(JOYAXISMOTION)
	ARG(JOYBALLMOTION)
	ARG(JOYHATMOTION)
//	ARG(JOYBUTTONMOTION)
	ARG(JOYBUTTONDOWN)
	ARG(JOYBUTTONUP)
	ARG(JOYDEVICEADDED)
	ARG(JOYDEVICEREMOVED)
	ARG(CONTROLLERAXISMOTION)
	ARG(CONTROLLERBUTTONDOWN)
	ARG(CONTROLLERBUTTONUP)
	ARG(CONTROLLERDEVICEADDED)
	ARG(CONTROLLERDEVICEREMOVED)
//	ARG(CONTROLLERDEVICEREMAPPED)
	ARG(FINGERDOWN)
	ARG(FINGERUP)
	ARG(FINGERMOTION)
	ARG(DOLLARGESTURE)
	ARG(MULTIGESTURE)
	ARG(CLIPBOARDUPDATE)
	ARG(DROPFILE)
//	ARG(AUDIODEVICEADDED)
//	ARG(AUDIODEVICEREMOVED)
	ARG(RENDER_TARGETS_RESET)
//	ARG(RENDER_DEVICE_RESET)
	// SDL_WindowEventID
	ARG(WINDOWEVENT_SHOWN)
	ARG(WINDOWEVENT_HIDDEN)
	ARG(WINDOWEVENT_EXPOSED)
	ARG(WINDOWEVENT_MOVED)
	ARG(WINDOWEVENT_RESIZED)
	ARG(WINDOWEVENT_SIZE_CHANGED)
	ARG(WINDOWEVENT_MINIMIZED)
	ARG(WINDOWEVENT_MAXIMIZED)
	ARG(WINDOWEVENT_RESTORED)
	ARG(WINDOWEVENT_ENTER)
	ARG(WINDOWEVENT_LEAVE)
	ARG(WINDOWEVENT_FOCUS_GAINED)
	ARG(WINDOWEVENT_FOCUS_LOST)
	ARG(WINDOWEVENT_CLOSE)
	// SDL_eventaction
	ARG(ADDEVENT)
	ARG(PEEKEVENT)
 	ARG(GETEVENT)
	END
	};
	for (auto r=args; r->name; ++r)
	{
	 lua_pushinteger(state, r->value);
	 lua_setfield(state, -2, r->name);
	}
	luaL_Reg regs [] = 
	{
//	REG(AddEventWatch)
//	REG(DelEventWatch)
	REG(EventState)
//	REG(FilterEvents)
	REG(FlushEvent)
	REG(FlushEvents)
//	REG(GetEventFilter)
	REG(GetNumTouchDevices)
	REG(GetNumTouchFingers)
	REG(GetTouchDevice)
	REG(GetTouchFinger)
	REG(HasEvent)
	REG(HasEvents)
	REG(LoadDollarTemplates)
	REG(PeepEvents)
//	REG(PollEvents)
	REG(PumpEvents)
	REG(PushEvent)
//	REG(QuitRequested)
	REG(RecordGesture)
	REG(RegisterEvents)
	REG(SaveAllDollarTemplates)
	REG(SaveDollarTemplate)
//	REG(SetEventFilter)
	REG(WaitEvent)
	REG(WaitEventTimeout)
	END
	};
	luaL_setfuncs(state, regs, 0);
	return 1;
}
 
